config/routes.rb
Todoodly::Application.routes.draw do

  root to: 'main#home'
  
  resources :lists do
  	resources :tasks
  end
  
  match 'home' => 'main#home', as: :home
  
  match 'lists/:list_id/tasks/:id/complete' => 'tasks#complete', as: :complete_task
  match 'lists/:list_id/tasks/:id/sort' => 'tasks#sort', as: :sort_task
  
  match 'signup' => 'users#new', as: :signup
  match 'users/create' => 'users#create', as: :users
  
  match 'login' => 'users#login', as: :login
  match 'validate' => 'users#log_in', as: :validate
  match 'logout' => 'users#log_out', as: :logout
  
  namespace :api do
  	resources :lists do
  		resources :tasks
  	end
  end
  
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :description, :name
  
  validates_presence_of :name
  
  has_many :tasks, dependent: :destroy
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :completed, :description, :list_id
  
  belongs_to :list
  
  scope :completed, where(:completed => true)
  scope :incomplete, where(:completed => false)
  scope :positioned, order('position ASC')
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password_digest, :password, :password_confirmation
  
  has_secure_password
  validates_presence_of :password, :on => :create
  
  has_many :lists
end

app/controllers/api/lists_controller.rb
class Api::ListsController < ApplicationController

	respond_to :json, :xml

	def index
		@lists = List.all
		@response = {}
		
		if @lists.empty?
			@response = {
				error: true,
				message: 'No lists available',
				data: ''
			}
		else
			@response = {
				error: false,
				message: 'Lists',
				data: @lists
			}
		end
		
		respond_with @response
	end
	
	def show
		begin
			@list = List.find(params[:id])
			@response = {
				error: false,
				message: "List: #{@list.name}",
				data: @list
			}
		rescue ActiveRecord::RecordNotFound
			@response = {
				error: true,
				message: "No list found",
				data: ""
			}
		end
		
		respond_with @response
	end

end

app/controllers/api/tasks_controller.rb
class Api::TasksController < ApplicationController

	respond_to :json, :xml
	
	def index
		@list = List.find(params[:list_id])
		@tasks = @list.tasks
		
		if @tasks.empty?
			@response = {
				error: true,
				message: 'No tasks available',
				data: ''
			}
		else
			@response = {
				error: false,
				message: 'Tasks',
				data: @tasks
			}
		end
		
		respond_with @response
	end
	
	def show
		begin
			@list = List.find(params[:list_id])
			@task = @list.tasks.find(params[:id])
			@response = {
				error: false,
				message: "Task: #{@task.description}",
				data: @task
			}
		rescue ActiveRecord::RecordNotFound
			@response = {
				error: true,
				message: "No task found with this id",
				data: ""
			}
		end
		
		respond_with @response
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  private
  
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	respond_to :html, :xml, :js
	before_filter :login_required

	def index
		user = current_user
		@lists = user.lists
		respond_with @lists
	end
	
	def new
		@list = List.new
	end
	
	def create
		@list = List.new(params[:list])
		@list.user_id = session[:user_id]
		if @list.save
			flash[:notice] = 'List created.'
			redirect_to list_url(@list)
		else
			flash[:error] = 'Could not create the list'
			redirect_to new_list_url
		end
	end
	
	def show
		begin
			user = current_user
			@list = user.lists.find(params[:id])
			@task = @list.tasks.new
		rescue ActiveRecord::RecordNotFound
			flash[:error] = "No list with id ##{params[:id]}"
			redirect_to lists_path
		end
	end
	
	def edit
		@list = List.find(params[:id])
	end
	
	def update
		@list = List.find(params[:id])
		if @list.update_attributes(params[:list])
			flash[:notice] = 'List updated'
			redirect_to list_path(@list)
		else
			flash[:error] = 'Could not update the list'
			redirect_to edit_list_path(@list)
		end
	end
	
	def destroy
		@list = List.find(params[:id])
		if @list.destroy
			flash[:notice] = 'List deleted'
			redirect_to lists_path
		else
			flash[:error] = 'Could not delete the list'
			redirect_to lists_path
		end
	end
	
	private
	def login_required
		unless current_user
			redirect_to login_path
		end
	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def home
		if current_user
			redirect_to lists_path
		end
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	
	respond_to :html, :xml, :js
	
	def create
		@list = List.find(params[:list_id])
		@task = @list.tasks.new(params[:task])
		if @task.save
			flash[:notice] = 'Task created'
			redirect_to list_path(@list)
		else
			flash[:error] = 'Could not add task'
			redirect_to list_path(@list)
		end
	end
	
	def complete
		@list = List.find(params[:list_id])
		@task = @list.tasks.find(params[:id])
		@task.completed = true
		@task.save
		flash[:notice] = 'Task completed'
		redirect_to list_path(@list)
	end
	
	def sort
		@list = List.find(params[:list_id])
		@tasks = @list.tasks.incomplete
		@tasks.each do |task|
			task.position = params[:task].index(task.id.to_s) + 1
			task.save
		end
		render :nothing => true
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
		for user in @users
			@text = user.name
		end
		
		render :text => @text
	end

	def new
		@user = User.new
	end
	
	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to login_path, :notice => "Signed up!"
		else
			render "new"
		end
	end
	
	def login
		
	end
	
	def log_in
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = 'Logged in!'
			redirect_to root_url
		else
			flash[:error] = 'Invalid email or password'
			redirect_to login_path
		end
	end
	
	def log_out
		session[:user_id] = nil
		flash[:notice] = 'Logged out!'
		redirect_to root_url
	end

end

app/helpers/api/lists_helper.rb
module Api::ListsHelper
end

app/helpers/api/tasks_helper.rb
module Api::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoodly</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div class="wrap">
		<% if flash[:notice] %>
			<div class="notice margin-bottom">
				<p><%= flash[:notice] %></p>
			</div>
		<% end %>
		
		<% if flash[:error] %>
			<div class="error margin-bottom">
				<p><%= flash[:error] %></p>
			</div>
		<% end %>
			
		<%= yield %>
	</div>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |form| %>

	<label>Name:
		<p><%= form.text_field :name %></p>
	</label>
	
	<label>Description:
		<p><%= form.text_field :description %></p>
	</label>
	
	<p><%= form.submit %></p>
	
<% end %>

app/views/lists/edit.html.erb
<%= render 'main/header' %>
<h1>Edit this list</h1>

<%= render 'form' %>

<br/>
<hr/>

<%= link_to 'Back to all lists', lists_path, class: 'back_link' %>
<div class="clear"></div>

app/views/lists/index.html.erb
<%= render 'main/header' %>
<h1>Lists</h1>

<hr/>
<br/>

<% if @lists.empty? %>
	<h3 class="empty">No lists yet...</h3>
<% else %>
	<% @lists.each do |list| %>
		
		<div class="list">
			<h3><%= link_to "#{list.name}", list_url(list) %></h3>
			<p>(<%= list.description %>)</p>
			<br/>
			<%= link_to 'Edit', edit_list_path(list), class: 'action' %>
			<%= link_to 'Delete', list_path(list), method: :delete, class: 'action' %>
		</div>
		
	<% end %>
<% end %>

<br/>
<hr/>

<%= link_to 'Add new list', new_list_url, class: 'new_link' %>
<div class="clear"></div>

app/views/lists/new.html.erb
<%= render 'main/header' %>
<h1>New Todo List</h1>

<%= render 'form' %>

<br/>
<hr/>

<%= link_to 'Back to all lists', lists_path, class: 'back_link' %>
<div class="clear"></div>

app/views/lists/show.html.erb
<%= render 'main/header' %>
<h1><%= @list.name %></h1>

<hr/>
<br/>

<% if @list.tasks.incomplete.empty? %>
	<h3 class="no_tasks">No tasks yet...</h3>
<% else %>
	<ul class="tasks">
		<% @list.tasks.positioned.incomplete.each do |task| %>
			<li id="task_<%=task.id%>">
				<%= hidden_field_tag 'list_id', @list.id %>
				<%= hidden_field_tag 'task_id', task.id %>
				<span class="handle">[=]</span>
				<%= link_to 'Complete', complete_task_path(@list.id,task.id), class: 'complete_button' %>
				<p><%= task.description %></p>
			</li>
			
		<% end %>
	</ul>
<% end %>

<%= form_for [@list, @task] do |form| %>
	<p><%= form.text_field :description %> <%= form.submit %></p>
<% end %>

<br/>
<hr/>

<%= link_to 'Back to all lists', lists_path, class: 'back_link' %>
<div class="clear"></div>

app/views/main/_header.html.erb
<header>
	<h2>Hey! Welcome <%= User.find(session[:user_id]).name %>.</h2>
	<%= link_to 'Logout', logout_path %>
	<div class="clear"></div>
</header>

app/views/main/home.html.erb
<h1>Todoodly</h1>
<p>Your todo list fav application</p>

<%= link_to "Sign up", signup_path %>
<%= link_to "Log in", login_path %>

app/views/users/login.html.erb
<h1>Log in</h1>

<%= form_tag validate_path do %>
	<div class="field">
		<%= label_tag :email %>
		<%= text_field_tag :email, params[:email] %>
	</div>
	
	<div class="field">
		<%= label_tag :password %>
		<%= password_field_tag :password %>
	</div>
	
	<div class="action">
		<%= submit_tag "Log in" %>
	</div>
<% end %>

<br/>
<hr/>

<%= link_to 'Go to home', root_path, class: 'back_link' %>
<div class="clear"></div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	
	<% if @user.errors.any? %>
		<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @user.errors.full_messages %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	
	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	
	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	
	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	
	<div class="action">
		<%= f.submit %>
	</div>
	
<% end %>

<br/>
<hr/>

<%= link_to 'Go to home', root_path, class: 'back_link' %>
<div class="clear"></div>